//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANQUE
    {
        public BANQUE()
        {
            this.EMPORT_ENRGT_SUR = new HashSet<EMPORT_ENRGT_SUR>();
        }
    
        public int ID_RES { get; set; }
        public Nullable<int> ID_GRP_BNQ { get; set; }
        public string ID_SIE { get; set; }
        public string ID_PUBLIC { get; set; }
        public bool EST_MOD_LOCAL { get; set; }
        public string CBQ { get; set; }
    
        public virtual ICollection<EMPORT_ENRGT_SUR> EMPORT_ENRGT_SUR { get; set; }
        public virtual GRP_BNQ GRP_BNQ { get; set; }
        public virtual PST_OPERATEUR PST_OPERATEUR { get; set; }
    }
}
