//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSM_VOL_CNT
    {
        public int ID_BSM { get; set; }
        public string CIE { get; set; }
        public string LIG { get; set; }
        public short JEX { get; set; }
        public string AER { get; set; }
    
        public virtual BSM BSM { get; set; }
    }
}
