//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRE_IND
    {
        public int ID_CRENEAU_INDISPO { get; set; }
        public Nullable<int> ID_RES_LIG_ENT_TRI { get; set; }
        public Nullable<int> ID_RES_EDS { get; set; }
        public Nullable<int> ID_RES_PST_OPERATEUR { get; set; }
        public Nullable<int> ID_RES_TOMO { get; set; }
        public Nullable<int> ID_RES_SORTIE_TRI { get; set; }
        public Nullable<int> ID_RES_TRONCON { get; set; }
        public System.DateTime TDEB_INDISPO { get; set; }
        public System.DateTime TFIN_INDISPO { get; set; }
        public string COMMENTAIRE { get; set; }
        public string TYPE_RES { get; set; }
        public string NOM_RES { get; set; }
        public string TYPE_INDISPO { get; set; }
    
        public virtual EDS ED { get; set; }
        public virtual LIG_ENT_TRI LIG_ENT_TRI { get; set; }
        public virtual PST_OPERATEUR PST_OPERATEUR { get; set; }
        public virtual SORTIE_TRI SORTIE_TRI { get; set; }
        public virtual TOMO TOMO { get; set; }
        public virtual TRONCON TRONCON { get; set; }
    }
}
