//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRP_TRI
    {
        public GRP_TRI()
        {
            this.EDS = new HashSet<EDS>();
            this.LIG_ENT_TRI = new HashSet<LIG_ENT_TRI>();
            this.PST_OPERATEUR = new HashSet<PST_OPERATEUR>();
            this.TOMOes = new HashSet<TOMO>();
            this.SORTIE_TRI = new HashSet<SORTIE_TRI>();
            this.TRONCONs = new HashSet<TRONCON>();
        }
    
        public int ID_GRP_TRI { get; set; }
        public int ID_MODE { get; set; }
        public string NOM_GRP_TRI { get; set; }
        public string LIB { get; set; }
        public string MOD_SAISIE_PIM { get; set; }
        public bool AVEC_TRACABILITE { get; set; }
        public bool BAG_FORCE_PIM { get; set; }
        public string MODE_EXPL { get; set; }
        public string OBS { get; set; }
    
        public virtual ICollection<EDS> EDS { get; set; }
        public virtual ICollection<LIG_ENT_TRI> LIG_ENT_TRI { get; set; }
        public virtual ICollection<PST_OPERATEUR> PST_OPERATEUR { get; set; }
        public virtual ICollection<TOMO> TOMOes { get; set; }
        public virtual ICollection<SORTIE_TRI> SORTIE_TRI { get; set; }
        public virtual ICollection<TRONCON> TRONCONs { get; set; }
    }
}
