//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIG_ENT_TRI
    {
        public LIG_ENT_TRI()
        {
            this.CRE_IND = new HashSet<CRE_IND>();
            this.EMPORT_VOLS = new HashSet<EMPORT_VOLS>();
            this.GRP_BNQ = new HashSet<GRP_BNQ>();
            this.TAC_ENTREE_TRI = new HashSet<TAC_ENTREE_TRI>();
            this.PST_OPERATEUR = new HashSet<PST_OPERATEUR>();
        }
    
        public int ID_RES { get; set; }
        public int ID_GRP_TRI { get; set; }
        public string TYP_LIG { get; set; }
        public string MOD_EXPL_LOC { get; set; }
        public string MODE_EXPL_SURETE { get; set; }
        public string NIV_AEROGARE { get; set; }
        public string EDS_ORIG_DEST { get; set; }
        public bool EST_DISP_IFBS { get; set; }
        public bool EST_FORCE_IFBS { get; set; }
        public Nullable<bool> EST_SECTORISEE { get; set; }
        public string OBS { get; set; }
        public Nullable<float> TAUX_ENVOI_PIM { get; set; }
        public Nullable<float> TAUX_ENVOI_CBSN1 { get; set; }
        public Nullable<float> TAUX_ENVOI_CBSN3 { get; set; }
        public Nullable<float> TAUX_RECEPTION_CORRESPONDANCE { get; set; }
        public Nullable<int> CAPA_MAX { get; set; }
        public Nullable<int> CAPA_TYP { get; set; }
        public string NOM_RES { get; set; }
        public string LIB { get; set; }
    
        public virtual ICollection<CRE_IND> CRE_IND { get; set; }
        public virtual ICollection<EMPORT_VOLS> EMPORT_VOLS { get; set; }
        public virtual ICollection<GRP_BNQ> GRP_BNQ { get; set; }
        public virtual GRP_TRI GRP_TRI { get; set; }
        public virtual ICollection<TAC_ENTREE_TRI> TAC_ENTREE_TRI { get; set; }
        public virtual ICollection<PST_OPERATEUR> PST_OPERATEUR { get; set; }
    }
}
