//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOD_CHR
    {
        public MOD_CHR()
        {
            this.EMPORT_VOLS = new HashSet<EMPORT_VOLS>();
        }
    
        public int ID_MOD_CHR { get; set; }
        public string LIB { get; set; }
        public string HDEPREF { get; set; }
        public short DANT { get; set; }
        public short DOUVTRI { get; set; }
        public short DFTRI { get; set; }
        public short DFDM { get; set; }
        public short DRATES { get; set; }
        public bool EST_OBSOLETE { get; set; }
    
        public virtual ICollection<EMPORT_VOLS> EMPORT_VOLS { get; set; }
    }
}
