//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCCURENCE_BAGAGE
    {
        public OCCURENCE_BAGAGE()
        {
            this.TRACE_BAGAGE = new HashSet<TRACE_BAGAGE>();
        }
    
        public int ID_BAGAGE { get; set; }
        public Nullable<int> ID_BSM { get; set; }
        public string CLEF_GLOBALE { get; set; }
        public string CODE_IATA { get; set; }
        public Nullable<System.DateTime> TENTREE_TRI { get; set; }
        public string ID_LOC_ENTREE { get; set; }
        public Nullable<bool> HORS_FORMAT { get; set; }
        public Nullable<int> DESTINATION1 { get; set; }
        public Nullable<int> DESTINATION2 { get; set; }
        public Nullable<int> DESTINATION3 { get; set; }
        public Nullable<int> DESTINATION4 { get; set; }
        public string STATUT_RATE { get; set; }
        public string STATUT_EJEC { get; set; }
        public string INDIC_SECTOR { get; set; }
        public string ANO_TRI { get; set; }
        public string ANO_SURETE { get; set; }
        public int ORDRE_APPARITION { get; set; }
        public string CIE { get; set; }
        public string CEC { get; set; }
        public string LIG { get; set; }
        public string JEX { get; set; }
        public string ENCOURS { get; set; }
        public Nullable<int> DIRECTIONENCOURS { get; set; }
        public Nullable<int> STATUT_SURETE_EJECTION { get; set; }
        public string TYPE_TACHE_1 { get; set; }
        public Nullable<int> ID_TACHE_1 { get; set; }
        public string TYPE_TACHE_2 { get; set; }
        public Nullable<int> ID_TACHE_2 { get; set; }
        public string TYPE_TACHE_3 { get; set; }
        public Nullable<int> ID_TACHE_3 { get; set; }
        public string TYPE_TACHE_4 { get; set; }
        public Nullable<int> ID_TACHE_4 { get; set; }
    
        public virtual BSM BSM { get; set; }
        public virtual ICollection<TRACE_BAGAGE> TRACE_BAGAGE { get; set; }
    }
}
