//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARK_AVION
    {
        public int ID_PARKING { get; set; }
        public string CODE_PARKING { get; set; }
        public string ID_SARIA_PARKING { get; set; }
        public short TPS_THEO_DEP_C { get; set; }
        public short TPS_THEO_DEP_R { get; set; }
        public string OBS { get; set; }
    }
}
