//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_BSM
    {
        public PART_BSM()
        {
            this.BSMs = new HashSet<BSM>();
        }
    
        public int ID_PART { get; set; }
        public string PART { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<BSM> BSMs { get; set; }
    }
}
