//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIM
    {
        public int ID_RES { get; set; }
        public string ID_LIG_SURETE { get; set; }
        public short NB_MAX_BAGS_ACCUMULES { get; set; }
        public int NB_BAG_TYPIQUE { get; set; }
        public int NB_BAG_MAX { get; set; }
    
        public virtual PST_OPERATEUR PST_OPERATEUR { get; set; }
    }
}
