//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACE_BAGAGE
    {
        public int ID_TRACE_BAG { get; set; }
        public int ID_BAGAGE { get; set; }
        public System.DateTime TTRACE { get; set; }
        public int ID_LOC { get; set; }
        public int TYPE { get; set; }
        public Nullable<int> STATUT { get; set; }
        public string INFO { get; set; }
    
        public virtual OCCURENCE_BAGAGE OCCURENCE_BAGAGE { get; set; }
    }
}
