//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOL
    {
        public VOL()
        {
            this.BSMs = new HashSet<BSM>();
            this.ITIs = new HashSet<ITI>();
        }
    
        public int ID_VOL { get; set; }
        public int ID_CIE { get; set; }
        public Nullable<int> ID_CEC { get; set; }
        public string LIG { get; set; }
        public short JEX { get; set; }
        public short QRF { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public string SPK { get; set; }
        public string STA { get; set; }
        public string DOA { get; set; }
        public string PKG { get; set; }
        public bool EST_VOL_DEP { get; set; }
        public string TDH { get; set; }
        public string NAT { get; set; }
        public Nullable<System.DateTime> REP { get; set; }
        public bool EST_FORCE_IFBS { get; set; }
        public bool EST_DISP_IFBS { get; set; }
    
        public virtual ICollection<BSM> BSMs { get; set; }
        public virtual ICollection<ITI> ITIs { get; set; }
        public virtual VOL_ARRIVE VOL_ARRIVE { get; set; }
        public virtual VOL_DEPART VOL_DEPART { get; set; }
    }
}
