//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOL_ARRIVE
    {
        public int ID_VOL { get; set; }
        public string AER_ORIGINE { get; set; }
        public bool CTRL_SUR_OK { get; set; }
    
        public virtual VOL VOL { get; set; }
    }
}
